import "Inspectable.idl";
import "Windows.UI.Xaml.Controls.idl";

namespace RuntimeApplication
{
	interface IMainPage;
	runtimeclass MainPage;
}

namespace RuntimeApplication
{
	[uuid(5b652990-b456-4709-add5-defb020e441e)]
	[exclusiveto(MainPage)]
	[version(0x00000001)]
	interface IMainPage : IInspectable
	{
		HRESULT InitializeComponent();
	}

	[activatable(0x00000001)]
	[marshaling_behavior(agile)]
	[threading(both)]
	[version(0x00000001)]
	runtimeclass MainPage : Windows.UI.Xaml.Controls.Page
	{
		[default] interface IMainPage;
	}
}