import "inspectable.idl";
import "Windows.ApplicationModel.Background.idl";

namespace RuntimeComponent
{
	runtimeclass TestClass;

	[version(1.0)]
	[uuid(aba6712e-a962-458c-8f2c-31617488a320)]
	[exclusiveto(TestClass)]
	interface ITestClassFactory : IInspectable
	{
		[overload("ActivateInstance")]HRESULT ActivateInstance0([in] INT32 value, [out, retval] TestClass** result);
		[overload("ActivateInstance")]HRESULT ActivateInstance1([in] INT32 value, [in] INT32 power, [out, retval] TestClass** result);
	};

	[exclusiveto(TestClass)]
	[version(1.0)]
	[uuid(67214cd3-3c60-4844-aa3b-a234f99f3c47)]
	interface ITestClass : IInspectable
	{
		[propget]
		HRESULT Int([out, retval] INT32* result);

		[propget]
		HRESULT Str([out, retval] HSTRING* result);
	};


	[exclusiveto(TestClass)]
	[version(1.0)]
	[uuid(67214cd3-3c60-4844-aa3b-a234f99f3c49)]
	interface ITestClass2 : IInspectable
	{
		[propget]
		HRESULT Long([out, retval] INT64* result);
	};

	[version(1.0)]
	[activatable(1.0)]
	[activatable(ITestClassFactory, 1.0)]
	[marshaling_behavior(agile)]
	[threading(both)]
	runtimeclass TestClass
	{
		[default] interface ITestClass;
		interface ITestClass2;
	};
}