import "inspectable.idl";
import "Windows.ApplicationModel.Background.idl";

#define VERSION 0x00000001

namespace MTLTestComponent
{
	runtimeclass TestClass;
}

namespace MTLTestComponent
{
	[activatable(VERSION)]
	[marshaling_behavior(agile)]
	[threading(both)]
	[version(VERSION)]
	runtimeclass TestTask
	{
		[default]
		interface Windows.ApplicationModel.Background.IBackgroundTask;
	};
}